"""6-DoF rigid body dynamics module.

This module contains the classical Newton-Euler differential equations
for simulating the dynamic behavior of the UAV in a 3D environment.

Author: Lucas Maroun de Almeida
"""

import numpy as np
# from numba import njit

# Global constant
GRAVITY: float = 9.81  # Gravity acceleration in m/s^2


# @njit
def six_dof_model(
    state: np.ndarray,
    ac_params: np.ndarray,
    wind_ned: np.ndarray,
    w_cmds: np.ndarray
) -> np.ndarray:
    """Calculates the state derivatives of the quadcopter using Newton-Euler formalism.

    Args:
        state (np.ndarray): The current state vector consisting of 20 elements:
            [0:3]   u, v, w         -> Linear velocities (Body Frame)
            [3:6]   p, q, r         -> Angular velocities (Body Frame)
            [6:9]   phi, theta, psi -> Euler angles (Inertial Frame)
            [9:12]  px, py, pz      -> Linear positions (Inertial Frame)
            [12:20] w, alpha        -> Angular velocities and accelerations per motor
        ac_params (np.ndarray): Aircraft physical and aerodynamic parameters.
        wind_ned (np.ndarray): Wind vector in NED Cartesian coordinates [wx, wy, wz].
        w_cmds (np.ndarray): Reference angular velocity for each motor [rad/s].

    Returns:
        np.ndarray: A vector containing the 20 state derivatives.
    """
    dx = np.zeros(20)

    # State variables extraction
    u, v, w = state[0], state[1], state[2]
    p, q, r = state[3], state[4], state[5]
    phi, theta, psi = state[6], state[7], state[8]

    # Motors (Angular velocity and angular acceleration)
    w_m1, alpha_m1 = state[12], state[13]
    w_m2, alpha_m2 = state[14], state[15]
    w_m3, alpha_m3 = state[16], state[17]
    w_m4, alpha_m4 = state[18], state[19]

    # Aircraft parameters extraction
    (mass, jx, jy, jz, jxz, cd, k_t0, k_q0,
     tau, kp, xi, dx_arm, dy_fw, dy_bw) = ac_params

    # Pre-calculation of trigonometric operations
    s_phi, c_phi = np.sin(phi), np.cos(phi)
    s_theta, c_theta, t_theta = np.sin(theta), np.cos(theta), np.tan(theta)
    s_psi, c_psi = np.sin(psi), np.cos(psi)

    # Gravity decomposed into the body coordinate system
    gb_x = -GRAVITY * s_theta
    gb_y = GRAVITY * s_phi * c_theta
    gb_z = GRAVITY * c_phi * c_theta

    wx_ned, wy_ned, wz_ned = wind_ned[0], wind_ned[1], wind_ned[2]

    # Wind transformation (Inertial NED to Body frame)
    wx_b = (
        wx_ned * (c_theta * c_psi)
        + wy_ned * (c_theta * s_psi)
        - wz_ned * s_theta
    )

    wy_b = (
        wx_ned * ((-c_phi * s_psi) + (s_phi * s_theta * c_psi))
        + wy_ned * ((c_phi * c_psi) + (s_phi * s_theta * s_psi))
        + wz_ned * (s_phi * c_theta)
    )

    wz_b = (
        wx_ned * ((s_phi * s_psi) + (c_phi * s_theta * c_psi))
        + wy_ned * ((-s_phi * c_psi) + (c_phi * s_theta * s_psi))
        + wz_ned * (c_phi * c_theta)
    )

    # ===== Motor Dynamics Modeling (2nd order system) ===== #
    tau_sq = tau ** 2
    dx[12] = alpha_m1
    dx[13] = ((-2.0 * xi * tau * alpha_m1) - w_m1 + (kp * w_cmds[0])) / tau_sq

    dx[14] = alpha_m2
    dx[15] = ((-2.0 * xi * tau * alpha_m2) - w_m2 + (kp * w_cmds[1])) / tau_sq

    dx[16] = alpha_m3
    dx[17] = ((-2.0 * xi * tau * alpha_m3) - w_m3 + (kp * w_cmds[2])) / tau_sq

    dx[18] = alpha_m4
    dx[19] = ((-2.0 * xi * tau * alpha_m4) - w_m4 + (kp * w_cmds[3])) / tau_sq

    # Thrust (T) and Torque (Q) calculation generated by each real motor
    t1 = k_t0 * (w_m1 ** 2)
    q1 = k_q0 * (w_m1 ** 2)
    
    t2 = k_t0 * (w_m2 ** 2)
    q2 = k_q0 * (w_m2 ** 2)
    
    t3 = k_t0 * (w_m3 ** 2)
    q3 = k_q0 * (w_m3 ** 2)
    
    t4 = k_t0 * (w_m4 ** 2)
    q4 = k_q0 * (w_m4 ** 2)

    # ===== Aerodynamic Forces (Body Frame) ===== #
    fx = -cd * (u - wx_b)
    fy = -cd * (v - wy_b)
    fz = -(t1 + t2 + t3 + t4) - (cd * (w - wz_b))

    # ===== External Moments (Body Frame) ===== #
    l = (t1 - t2) * dy_fw + (t4 - t3) * dy_bw
    m = (t1 + t2 - t3 - t4) * dx_arm
    n = -q1 + q2 - q3 + q4

    # ===== Translational Motion Equations ===== #
    dx[0] = (fx / mass) + gb_x - (q * w) + (v * r)
    dx[1] = (fy / mass) + gb_y - (p * w) + (u * r)
    dx[2] = (fz / mass) + gb_z - (p * v) + (u * q)

    # ===== Rotational Motion Equations ===== #
    den = (jx * jz) - (jxz ** 2)
    dx[3] = (1.0 / den) * (
        (jz * (jy - jz) - jxz**2) * q * r
        + jxz * (jx - jy + jz) * p * q
        + jz * l
        + jxz * n
    )
    dx[4] = (1.0 / jy) * (
        ((jz - jx) * r * p) - (jxz * (p**2 - r**2)) + m
    )
    dx[5] = (1.0 / den) * (
        (jx * (jx - jy) + jxz**2) * p * q
        + jxz * (jy - jx - jz) * q * r
        + jxz * l
        + jx * n
    )

    # ===== Euler Kinematics ===== #
    dx[6] = p + (q * s_phi * t_theta) + (r * c_phi * t_theta)
    dx[7] = (q * c_phi) - (r * s_phi)
    dx[8] = (q * s_phi / c_theta) + (r * c_phi / c_theta)

    # ===== Position Equations ===== #
    dx[9] = (
        u * (c_theta * c_psi)
        + v * ((-c_phi * s_psi) + (s_phi * s_theta * c_psi))
        + w * ((s_phi * s_psi) + (c_phi * s_theta * c_psi))
    )

    dx[10] = (
        u * (c_theta * s_psi)
        + v * ((c_phi * c_psi) + (s_phi * s_theta * s_psi))
        + w * ((-s_phi * c_psi) + (c_phi * s_theta * s_psi))
    )

    dx[11] = (
        u * (-s_theta)
        + v * (s_phi * c_theta)
        + w * (c_phi * c_theta)
    )

    return dx